### ISSUE TITLE
Core creation when deploying with docker-compose

### ISSUE THREAD

**Issue by jussiviitamaki** [wodby/drupal-solr#1]
Is there any way to create a core automatically when deploying the stack with docker-compose?

I've tried to create a custom script and modified entrypoint.sh to run it while deploying but no avail. 
I have found that that's because script gets executed before Solr is actually started and if I modify Solr to start before running core creation script the script doesn't run ever because Solr starts on foreground.

**Comment by csandanov** [comment]
We provide `init` action in the base [wodby/solr](https://github.com/wodby/solr#orchestration-actions) image, it will create a solr core named "default" if no cores exist. You can run it via `docker exec --rm [CID] make init -f /usr/local/bin/actions.mk` for existing container. Or you can use `create` action to create your own core.

**Comment by divined** [comment]
unknown flag: --rm
See 'docker exec --help'.

**Comment by csandanov** [comment]
I'm sorry, remove `--rm`, it's not necessary for exec.

**Comment by molfar** [comment]
But why this default core hasn't created automatically?

**Comment by csandanov** [comment]
Before creating a solr core you should first make sure your solr server is up and running, in other words, perform a healthiness probe that happens outside of the container, and only when it's passed you should create a core.
